name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: ArnaudBaley/fork-checkout@v2

      - name: Update theme    
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build
        run: hugo

      - name: Deploy
        uses: ArnaudBaley/fork-actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}        
          publish_dir: ./public
          keep_files: true
          publish_branch: docs